### ISSUE TITLE
Can't reproduce the ideal performance

### ISSUE THREAD

**Issue by ray075hl** [assafshocher/ZSSR#2]
hello @assafshocher, I run the code with this command on Set5
```
python run_ZSSR.py X2_ONE_JUMP_IDEAL_CONF 0
```
The LR images processing step as follow
First I used opencv convert Set5 HR images to YCbCr format, only saved Y channel of this images to calculate PSNR with SR images. Then, resized the Y channel with tool "assafshocher/Resizer", saved resized image as LR images, which are the inputs of ZSSR.
The final average PSNR of Set 5 I obtained is 35.3 much lower than 37.3
Is that my processing wrong?
Very appreciate for your help.

**Comment by assafshocher** [comment]
Hi @ray075hl ,
There are a few possible solutions:
- We use full RGB and not just luminance for running ZSSR.
- Try using python run_ZSSR.py X2_GRADUAL_IDEAL_CONF
- Evaluation is done by a common MATLAB script by Kime Et Al.  (basically taking only luminance, and cropping some deges)

**Comment by ray075hl** [comment]
@assafshocher  Thanks a lot!  I will try it.

**Comment by ray075hl** [comment]
I used  opencv  function cv2.cvtColor(img, cv2.COLOR_RGB2YCrCb) to get Y channel  have bit differents with matlab code convert rgb to Y.  Now I get the average psnr of Set5: 37.03.   
Thanks.
