### ISSUE TITLE
There are artifacts in output of real_example charlie.png

### ISSUE THREAD

**Issue by sczhou** [assafshocher/ZSSR#20]
Hi, I run the code using "python run_ZSSR.py X2_REAL_CONF", but I can't reproduce the same result with the result in the paper. The output has artifacts. The following is what I get:
![charlie_zssr_X2 00X2 00](https://user-images.githubusercontent.com/14334509/76701672-2ebbb000-66fe-11ea-8557-68f50aa6d50c.png)
I run it with py3. Do you have the solution to this problem?

Thanks.

**Comment by JulieG0916** [comment]
Hi,same problem here.Have you found the solution?😔

**Comment by sczhou** [comment]
I changed my Python version to Py2, thus, the problem was fixed.

**Comment by JulieG0916** [comment]
It really works, thank you so much!
