### ISSUE TITLE
KeyError: 'Kernel

### ISSUE THREAD

**Issue by Rainyliuliu** [assafshocher/ZSSR#3]
Hello, i meet a problem:KeyError: 'Kernel' , i think the problem is caused by following function. I wish for your reply. Thank you very much.
def preprocess_kernels(kernels, conf):
    # Load kernels if given files. if not just use the downscaling method from the configs.
    # output is a list of kernel-arrays or a a list of strings indicating downscaling method.
    # In case of arrays, we shift the kernels (see next function for explanation why).
    # Kernel is a .mat file (MATLAB) containing a variable called 'Kernel' which is a 2-dim matrix.
    if kernels is not None:

        return [kernel_shift(loadmat(kernel)['Kernel'], sf)
                for kernel, sf in zip(kernels, conf.scale_factors)]
    else:
        return [conf.downscale_method] * len(conf.scale_factors)

**Comment by assafshocher** [comment]
Thanks for letting me know!
That was a bug. The name of the variable inside the mat file was 'ker' and not 'Kernel' as it needs to be.
Fixed now,
Thanks!

**Comment by Rainyliuliu** [comment]
Thank you for your reply! I




| |
liu
邮箱：13233975665@163.com
|

Signature is customized by Netease Mail Master

On 10/10/2018 20:32, Assaf Shocher wrote:

Thanks for letting me know!
That was a bug. The name of the variable inside the mat file was 'ker' and not 'Kernel' as it needs to be.
Fixed now,
Thanks!
