### ISSUE TITLE
Question about weights of this model

### ISSUE THREAD

**Issue by KennethWang1221** [assafshocher/ZSSR#32]
Hello
could you provide the test model weights? I want to reference your method and test on my dataset, but I can not find your weights.

**Comment by assafshocher** [comment]
Hi,
ZSSR trains on test time so there are no pre-trained weights.
Just apply the procedure to your data.
Thanks!

**Comment by KennethWang1221** [comment]
Hi,
so you mean, I need re-train ZSSR on my training data and then use it to test my data ?
