### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by NoushNabi** [assafshocher/ZSSR#6]
Hello Assaf,
I am wondering if you have a pre-trained model for your method. If so, I appreciate if you point me to it.
Thanks,
N

**Comment by assafshocher** [comment]
Hi NoushNabi,
ZSSR is not pretrained, it trains quickly on test time over a single image, therefore pretrained weights cannot exist.

**Comment by NoushNabi** [comment]
Thank you very much for your reply.
