### ISSUE TITLE
Should be X2_IDEAL_WITH_PLOT_CONF 

### ISSUE THREAD

**Issue by jspiers** [assafshocher/ZSSR#9]
In your README.md, it looks like the command for "Visualization while running (Recommended for one image, interactive mode, for debugging)" should be:

python run_ZSSR.py X2_IDEAL_WITH_PLOT_CONF

Not as it is currently

python run_ZSSR.py X2_IDEAL_ONE_JUMP_IDEAL_CONF

**Comment by assafshocher** [comment]
Fixed.
Thank you so much!
